### ISSUE TITLE
Feedback zum Testat

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/repo-15#1]
Bitte korrigieren Sie die folgenden Fehler und checken Sie dann die korrigierte Version ein. Danach können Sie dieses Issue schließen.

  * JavaDoc für die Klasse selbst ergänzen, diese fehlt.
  * Ihre Implementierung geht nicht richtig mit Eingaben um, die ungültige Zeichen enthalten. Diese sollen stillschweigend entfernt werden.

**Comment by 1512836** [comment]
joh jetz passts
